services:
  api_issues:
    #build: .
    image: theruler/github_api_issues:v0.1.0b
    secrets:
      - token
    command: ./init.sh python main.py
    volumes:
     - github_issues:/usr/src/github_app/outputs

secrets:
  token:
    file: ./access_token.priv

volumes:
  github_issues: {}