[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Github issues scraper"
authors = [{name = "Huld", email = "cz_huld@huld.io"}]
dynamic = ["version", "description"]
