services:
  api_issues:
    #build: 
      #context: ../
      #dockerfile: docker/Dockerfile
    image: theruler/github_api_issues:latest
    secrets:
      - token
    environment: 
     - GITHUB_ADDRESS=${GITHUB_ADDRESS}
    entrypoint: ["sh", "-c", "chmod +x ./init.sh && ./init.sh python main.py ${GITHUB_ADDRESS}"]
    volumes:
     - github_issues:/usr/src/github_app/outputs

secrets:
  token:
    file: ../access_token.priv

volumes:
  github_issues: {}