name: Publish Docker image

# on:
#   release:
#     types: [published]

on:
  create:
    tags:
      - 'v*'
  workflow_dispatch :
    inputs:
      tags:
       description: 'Tag describing manual trigger'
       type: string
       required: false


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: theruler/github_api_issues
      
      - name: Get tag 
        id: step_tag1
        run: echo "tag_version=$(echo $GITHUB_REF | cut -d/ -f3)" >> $GITHUB_ENV

      - name: Put version into file 
        id: step_tag2
        run: echo ${{ env.tag_version }} >> version.txt

      - name: Show tag
        id: step_tag3
        run: echo ${{ env.tag_version }}

      - name: Show tag
        id: step_tag4
        run: echo ${{ github.ref }}
      
      - name: Show tag
        id: step_tag5
        run: echo $GITHUB_REF

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: | 
              VERSION_APP=${{ env.tag_version }}
              TAG_APP=${{ github.ref }}
